"use client"

import { useState } from "react"
import { SiteHeader } from "@/components/site-header"
import { AnalysisInputForm } from "@/components/analysis-input"
import { DistributionChart } from "@/components/distribution-chart"
import { ModelInsights } from "@/components/model-insights"
import type { AnalysisResult } from "@/lib/types"
import { Shield, ArrowDown } from "lucide-react"

export default function HomePage() {
  const [result, setResult] = useState<AnalysisResult | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  async function handleAnalysis(formData: FormData) {
    setIsLoading(true)
    setError(null)
    setResult(null)

    try {
      const response = await fetch("/api/analyze", {
        method: "POST",
        body: formData,
      })

      const data = await response.json()

      if (!response.ok) {
        throw new Error(data.error || `Analysis failed with status ${response.status}`)
      }

      setResult(data.result)
    } catch (err) {
      setError(err instanceof Error ? err.message : "Analysis failed. Please try again.")
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex flex-col">
      <SiteHeader />

      <main className="flex-1">
        {/* Input Section */}
        <section className="border-b border-border">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="mb-8">
              <h1 className="text-2xl font-semibold text-foreground tracking-tight text-balance">
                Fraud Signal Analysis
              </h1>
              <p className="text-sm text-muted-foreground mt-2 max-w-2xl leading-relaxed">
                Submit earnings call transcripts for AI-powered analysis.
                Signals are correlated with patterns observed in SEC Accounting and Auditing Enforcement Releases (AAERs).
                Our model detects fraud up to <span className="text-foreground font-medium">4 years early</span> using voice acoustics and language features.
              </p>
            </div>

            <AnalysisInputForm onSubmit={handleAnalysis} isLoading={isLoading} />

            {error && (
              <div className="mt-4 rounded-lg border border-destructive/30 bg-destructive/10 p-4">
                <p className="text-sm text-destructive font-mono">{error}</p>
              </div>
            )}
          </div>
        </section>

        {/* Loading State */}
        {isLoading && (
          <section className="border-b border-border">
            <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-16 flex flex-col items-center gap-4">
              <div className="relative">
                <div className="h-16 w-16 rounded-full border-2 border-primary/20 flex items-center justify-center">
                  <Shield className="h-8 w-8 text-primary animate-pulse" />
                </div>
                <div className="absolute inset-0 h-16 w-16 rounded-full border-2 border-primary border-t-transparent animate-spin" />
              </div>
              <div className="text-center">
                <p className="text-sm font-semibold text-foreground">Running Model</p>
                <p className="text-xs text-muted-foreground font-mono mt-1">
                  Extracting voice &amp; language features · computing fraud probability...
                </p>
              </div>
            </div>
          </section>
        )}

        {/* Results */}
        {result && (
          <section>
            <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
              <div className="flex flex-col gap-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <ArrowDown className="h-4 w-4 text-muted-foreground" />
                    <h2 className="text-lg font-semibold text-foreground">
                      Model Output
                    </h2>
                  </div>
                  <span className="text-xs text-muted-foreground font-mono">
                    {new Date().toISOString().split("T")[0]}
                  </span>
                </div>

                {/* Fraud probability distribution over horizons */}
                <DistributionChart result={result} />

                {/* Top features + model performance metrics */}
                <ModelInsights result={result} />

                <div className="rounded-lg border border-border bg-secondary/30 p-4">
                  <p className="text-xs text-muted-foreground font-mono leading-relaxed">
                    DISCLAIMER: This analysis is generated by our model for research and hackathon purposes only.
                    It does not constitute financial advice, legal advice, or an accusation of fraud.
                    The fraud probability distribution is a probabilistic assessment based on patterns in historical SEC enforcement data.
                    Always consult qualified professionals.
                  </p>
                </div>
              </div>
            </div>
          </section>
        )}

        {/* Empty state */}
        {!result && !isLoading && (
          <section>
            <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-16 flex flex-col items-center gap-4">
              <div className="h-16 w-16 rounded-full bg-secondary flex items-center justify-center">
                <Shield className="h-8 w-8 text-muted-foreground" />
              </div>
              <div className="text-center max-w-md">
                <p className="text-sm text-muted-foreground">
                  Upload all three inputs to detect early fraud signals.
                </p>
                <p className="text-xs text-muted-foreground font-mono mt-2">
                  Requires a .txt transcript, audio CSV, and quarterly report PDF
                  to run the fraud signal model and view the probability distribution.
                </p>
              </div>
            </div>
          </section>
        )}
      </main>

      <footer className="border-t border-border py-4">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between">
          <span className="text-xs text-muted-foreground font-mono">Fraud Signal Analytics · Hacklytics 2026</span>
          <span className="text-xs text-muted-foreground font-mono">LightGBM + SBERT · SEC AAER dataset</span>
        </div>
      </footer>
    </div>
  )
}
